# Generated by Django 5.0.7 on 2024-08-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_notice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roomate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobilenumber", models.CharField(max_length=10)),
                ("name", models.TextField()),
            ],
        ),
    ]
